# -*- coding: utf-8 -*-
"""fake_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/stepherbin/teaching/blob/master/IOGS/projet/LIAR2_fake_news/fake_test.ipynb

# Détection de Fake News

L'objectif est de prédire si des déclarations sont vraies ou fausses.

Les données sont celles de la base LIAR2

- accessible depuis Hugging Face: https://huggingface.co/datasets/chengxuphd/liar2
- ou depuis le Github https://github.com/chengxuphd/liar2 qui contient des codes et des références.

## Les données
### Chargement des données

Depuis Hugging-Face

Les données sont organisées en dictionnaires.
"""

import numpy as np
import datasets
import re

import nltk
# Interactive library download
#nltk.download()
nltk.download('punkt_tab')

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import os
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, accuracy_score
from sklearn.preprocessing import LabelEncoder
import torch
import torch.nn as nn
import torch.optim as optim
from transformers import BertTokenizer
from transformers import BertModel
from torch.utils.data import TensorDataset, DataLoader
from transformers import get_linear_schedule_with_warmup

dataset = "chengxuphd/liar2"
dataset = datasets.load_dataset(dataset)
statement_train, y_train = dataset["train"]["statement"], dataset["train"]["label"]
statement_val, y_val = dataset["validation"]["statement"], dataset["validation"]["label"]
statement_test, y_test = dataset["test"]["statement"], dataset["test"]["label"]

output_tags = ["Pants on fire","False","Barely-true","Half-true","Mostly-true","True"]

"""Depuis le Github de LIAR2

Les données sont téléchargées en fichier 'csv' et lus avec pandas.
"""

df_train = pd.read_csv('LIAR2/train.csv')
df_val = pd.read_csv('LIAR2/valid.csv')
df_test = pd.read_csv('LIAR2/test.csv')

"""Ajout de la crédibilité suivant l'auteur

"""
counts_cols = [
    "true_counts",
    "mostly_true_counts",
    "half_true_counts",
    "mostly_false_counts",
    "false_counts",
    "pants_on_fire_counts"
]

def compute_credibility(df):

    total = df[counts_cols].sum(axis=1)

    true_part = df["true_counts"]+df["mostly_true_counts"] + df["half_true_counts"]

    credibility = true_part / (total + 1e-6)

    return credibility

df_train["credibility"] = compute_credibility(df_train)
df_val["credibility"] = compute_credibility(df_val)
df_test["credibility"] = compute_credibility(df_test)


"""### Nettoyage des données

Les fonctions ci-dessous transforment les données brutes en une séquence de mots normalisés.
"""


# ensure NLTK resources available
nltk_packages = ["punkt", "stopwords", "wordnet", "omw-1.4"]
for pkg in nltk_packages:
    try:
        nltk.data.find(pkg)
    except LookupError:
        nltk.download(pkg)


STOPWORDS = set(stopwords.words("english"))
LEMMATIZER = WordNetLemmatizer()

def clean_text(text: str) -> str:
    """Basic cleanup: lowercase, remove urls, punctuation, extra spaces, stopwords, lemmatize."""
    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", " ", text)
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    tokens = nltk.word_tokenize(text)
    tokens = [t for t in tokens if t not in STOPWORDS and len(t) > 1]
    tokens = [LEMMATIZER.lemmatize(t) for t in tokens]
    return " ".join(tokens)

statement_train_clean = list(map(clean_text, statement_train))
statement_val_clean = list(map(clean_text, statement_val))
statement_test_clean = list(map(clean_text, statement_test))

"""### Nettoyage des données

Les fonctions ci-dessous transforment les données brutes en une séquence de mots normalisés en y ajoutant les metadonnées.
"""

# --- Fonction pour préparer les métadonnées ---
def prepare_metadata_encoders(df_train, columns_to_encode):
    encoders = {}
    for col in columns_to_encode:
        le = LabelEncoder()
        # On entraîne l'encodeur uniquement sur le train pour éviter le "data leakage"
        # Ajout d'une classe '<UNKNOWN>' pour gérer les valeurs inconnues
        unique_values = df_train[col].fillna('<UNKNOWN>').unique().tolist()
        if '<UNKNOWN>' not in unique_values:
            unique_values.append('<UNKNOWN>')
        le.fit(unique_values)
        encoders[col] = le
    return encoders

def encode_metadata(df, encoders, columns_to_encode):
    encoded_cols = []
    for col in columns_to_encode:
        le = encoders[col]
        # Mapper les valeurs, remplacer les inconnues par '<UNKNOWN>' avant transformation
        series = df[col].fillna('<UNKNOWN>')
        # Gérer les valeurs inconnues non vues lors de l'entraînement
        series = series.apply(lambda x: x if x in le.classes_ else '<UNKNOWN>')
        encoded_cols.append(torch.tensor(le.transform(series), dtype=torch.long))
    
    # Empiler les colonnes pour créer un tenseur [nb_echantillons, nb_features]
    return torch.stack(encoded_cols, dim=1)

# --- Colonnes à utiliser ---
columns_to_use = ['speaker', 'context', 'state_info','statement','subject'] # 'state' est souvent utile aussi

# --- Initialiser et entraîner les encodeurs ---
# Suppose que tu as extrait df_train, df_val, df_test qui contiennent ces colonnes
meta_encoders = prepare_metadata_encoders(df_train, columns_to_use)

# --- Encoder les métadonnées ---
train_meta = encode_metadata(df_train, meta_encoders, columns_to_use)
val_meta = encode_metadata(df_val, meta_encoders, columns_to_use)
# test_meta = encode_metadata(df_test, meta_encoders, columns_to_use)

# --- Stocker le nombre de catégories pour chaque feature (nécessaire pour les Embeddings) ---
meta_vocab_sizes = {col: len(meta_encoders[col].classes_) for col in columns_to_use}

"""### Génération des labels

Les données d'origine sont définies par un score de véracité à 6 niveaux.

Ici on transforme le problème en une classification binaire ("true", "Fake").
"""

y_test_binary = np.array([0 if i <= 2 else 1 for i in y_test])
y_train_binary = np.array([0 if i <= 2 else 1 for i in y_train])
y_val_binary = np.array([0 if i <= 2 else 1 for i in y_val])

"""## Premiers tests

### Transformation des données

Les déclarations sont des listes de taille variable.

On les transforme en vecteurs de taille fixe par la méthode des "bag of words", dans sa version Tf-Idf.
"""


vec = TfidfVectorizer(max_features=10000, ngram_range=(1, 2))
X_train = vec.fit_transform(statement_train_clean)
X_test = vec.transform(statement_test_clean)

print("Les données sont de dimension {:d}".format(X_train.shape[1]))
print("Le nombre de données d'apprentissage est {:d}".format(y_train_binary.shape[0]))

# Calcul du nombre moyens d'éléments non nuls
non_nul_moyen = np.mean(np.sum(X_train > 0,axis=1))
print("Le nombre moyen de valeurs non nulles par échantillon est {:.1f}".format(non_nul_moyen))

"""### Essais élémentaire de classification

Le code ci-dessous teste différents algorithmes du cours pour la classification binaire, avec
 leurs paramètres par défaut.

C'est une première base, clairement à améliorer.

En particulier, on peut utiliser un modèle de langage pour encoder les déclarations et travailler sur cette représentatino plutôt que sur le "bag of words".
"""



model_list = [MultinomialNB(),
              LinearSVC(max_iter=10000, C=0.1),
              LogisticRegression(max_iter=1000),
            #   RandomForestClassifier(n_estimators=200, n_jobs=-1)
              ]

for model in model_list:
    model.fit(X_train, y_train_binary)
    preds = model.predict(X_train)

    print("Erreurs de train/test pour le modèle {} est {:.2f} / {:.2f}%".format(
        model,
        100*(1-model.score(X_train, y_train_binary)),
        100*(1-model.score(X_test, y_test_binary))))

"""### Autres informations utilisables

Le jeu de données contient en plus de la déclaration ("statement") et de sa valeur de vérité ("label") des informations sur la data, le sujet, l'orateur, sa description, le lieu, le contexte de la déclaration, et une justification du score. Il contient aussi un historique pour chaque orateur de la véracité de ses déclarations ('counts').

Elle peuvent être utilisées pour améliorer la prédiction en exploitant les bons priors...
"""

'''
print(dataset['train'])
for i in range(4):
    print('statement: ', dataset['train']['statement'][i])
    print('speaker: ', dataset['train']['speaker'][i])
    print('speaker description: ', dataset['train']['speaker_description'][i])
    print('context: ', dataset['train']['context'][i])
    print('justification: ', dataset['train']['justification'][i])
    print('')
'''

df_train.head()

#%%
"""### Construction de notre résseau de neurones

Le code ci-dessous permet construit notre réseau de neuronnes et 
l'entraîne sur les données d'apprentissage.

En particulier, on peut utiliser un modèle de langage pour encoder les déclarations et travailler sur cette représentatino plutôt que sur le "bag of words".
"""




# conversion sparse matrix -> tensor
X_train_torch = torch.tensor(X_train.toarray(), dtype=torch.float32)
y_train_torch = torch.tensor(y_train_binary, dtype=torch.float32)

X_val = vec.transform(statement_val_clean)
X_val_torch = torch.tensor(X_val.toarray(), dtype=torch.float32)
y_val_torch = torch.tensor(y_val_binary, dtype=torch.float32)



class FakeNewsNet(nn.Module):

    def __init__(self, input_dim):

        super().__init__()

        self.model = nn.Sequential(
            nn.Linear(input_dim,256),
            nn.ReLU(),
            nn.Dropout(0.3),

            nn.Linear(256,64),
            nn.ReLU(),

            nn.Linear(64,1),
            nn.Sigmoid()
        )

    def forward(self,x):
        return self.model(x)
    

model = FakeNewsNet(X_train.shape[1])

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

epochs = 50
best_val = 0

for epoch in range(epochs):

    # -------------------
    # TRAIN
    # -------------------
    model.train()

    optimizer.zero_grad()

    outputs = model(X_train_torch).squeeze()

    loss = criterion(outputs, y_train_torch)

    loss.backward()

    optimizer.step()


    # -------------------
    # VALIDATION
    # -------------------
    model.eval()

    with torch.no_grad():

        val_outputs = model(X_val_torch).squeeze()

        val_preds = (val_outputs > 0.5).float()

        val_acc = (val_preds == y_val_torch).float().mean()

    if val_acc > best_val:
        best_val = val_acc
        torch.save(model.state_dict(), "best_model.pt")

    print(f"Epoch {epoch}")
    print("Train loss:", loss.item())
    print("Validation accuracy:", val_acc.item())

#%%
"""### Construction de notre résseau de neurones en utilisant BERT

Le code ci-dessous permet construit notre réseau de neuronnes et 
l'entraîne sur les données d'apprentissage.

En particulier, on peut utiliser un modèle de langage pour encoder les déclarations et travailler sur cette représentatino plutôt que sur le "bag of words".
"""



device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)



tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

train_texts = [
    s + " " + j if j is not None else s
    for s, j in zip(df_train["statement"], df_train["justification"])
]
val_texts = [
    s + " " + j if j is not None else s
    for s, j in zip(df_val["statement"], df_val["justification"])
]
test_texts = [
    s + " " + j if j is not None else s
    for s, j in zip(df_test["statement"], df_test["justification"])
]

train_cred = torch.tensor(df_train["credibility"].values, dtype=torch.float32).unsqueeze(1)
val_cred = torch.tensor(df_val["credibility"].values, dtype=torch.float32).unsqueeze(1)
test_cred = torch.tensor(df_test["credibility"].values, dtype=torch.float32).unsqueeze(1)


train_tokens = tokenizer(
    train_texts,
    padding=True,
    truncation=True,
    max_length=128,
    return_tensors="pt"
)

val_tokens = tokenizer(
    val_texts,
    padding=True,
    truncation=True,
    max_length=128,
    return_tensors="pt"
)

test_tokens = tokenizer(
    test_texts,
    padding=True,
    truncation=True,
    max_length=128,
    return_tensors="pt"
)

train_input_ids = train_tokens["input_ids"]
train_attention_mask = train_tokens["attention_mask"]

val_input_ids = val_tokens["input_ids"]
val_attention_mask = val_tokens["attention_mask"]

test_input_ids = test_tokens["input_ids"]
test_attention_mask = test_tokens["attention_mask"]

labels = torch.tensor(y_train_binary, dtype=torch.float32)
val_labels = torch.tensor(y_val_binary, dtype=torch.float32)

train_dataset = TensorDataset(
    train_input_ids,
    train_attention_mask,
    train_meta,
    train_cred,
    labels
)

val_dataset = TensorDataset(
    val_input_ids,
    val_attention_mask,
    val_meta,
    val_cred,
    val_labels
)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16)

class FakeNewsBERT(nn.Module):

    def __init__(self, meta_vocab_sizes, embedding_dim=32):

        super().__init__()

        # --- Branche Texte (BERT) ---
        self.bert = BertModel.from_pretrained("bert-base-uncased")

        # --- Branche Métadonnées (Embeddings) ---
        # meta_vocab_sizes est un dictionnaire {nom_colonne: taille_vocab}
        self.meta_embeddings = nn.ModuleDict({
            col: nn.Embedding(vocab_size, embedding_dim)
            for col, vocab_size in meta_vocab_sizes.items()
        })

        # --- Fusion et Classification ---
        # Dimension d'entrée du classifieur = BERT (768) + somme des embedding_dims
        total_meta_dim = len(meta_vocab_sizes) * embedding_dim
        classifier_input_dim = 768 + total_meta_dim+1 # pour la crédibilité

        self.classifier = nn.Sequential(
            nn.Linear(classifier_input_dim,512),
            nn.ReLU(),
            nn.Dropout(0.4),

            nn.Linear(512,128),
            nn.ReLU(),
            nn.Dropout(0.3),

            nn.Linear(128,1)
        )

    def forward(self, input_ids, attention_mask, meta_data,credibility):

        outputs = self.bert(
            input_ids=input_ids,
            attention_mask=attention_mask,
            return_dict=False
        )

        token_embeddings = outputs[0]
        attention_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()

        sum_embeddings = torch.sum(token_embeddings * attention_mask_expanded, 1)
        sum_mask = torch.clamp(attention_mask_expanded.sum(1), min=1e-9)

        cls_embedding = sum_embeddings / sum_mask
                
        # 2. Obtenir et concaténer les embeddings des métadonnées
        meta_embeds = []
        for i, (col, embed_layer) in enumerate(self.meta_embeddings.items()):
            # meta_data[:, i] extrait la i-ème colonne (la feature correspondante)
            encoded_feature = meta_data[:, i]
            meta_embeds.append(embed_layer(encoded_feature)) # [batch_size, embedding_dim]
            
        # Concaténer tous les embeddings de métadonnées
        meta_cat = torch.cat(meta_embeds, dim=1) # [batch_size, total_meta_dim]
        
        # 3. Fusionner Texte + Métadonnées
        combined_input = torch.cat((cls_embedding, meta_cat, credibility), dim=1) # [batch_size, classifier_input_dim]
        
        # 4. Classification
        return self.classifier(combined_input)


model = FakeNewsBERT(meta_vocab_sizes, embedding_dim=32).to(device)

for param in model.bert.parameters():
    param.requires_grad = False


fake_count = np.sum(y_train_binary == 0)
true_count = np.sum(y_train_binary == 1)
pos_weight = torch.tensor([fake_count/true_count]).to(device)
criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.AdamW([
    {"params": model.bert.parameters(), "lr": 2e-5},
    {"params": model.classifier.parameters(), "lr": 1e-3},
    {"params": model.meta_embeddings.parameters(), "lr": 1e-3}
])

epochs = 1


patience = 5
patience_counter = 0

total_steps = len(train_loader) * epochs

scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=int(0.1 * total_steps),
    num_training_steps=total_steps
)

print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

for epoch in range(epochs):

    # -------------------
    # TRAIN
    # -------------------
    if epoch == 5:
        print("Unfreezing BERT")
        for param in model.bert.parameters():
            param.requires_grad = True

    model.train()

    epoch_loss = 0

    for batch in train_loader:

        input_ids, attention_mask, batch_meta, batch_cred, batch_labels = batch

        input_ids = input_ids.to(device)
        attention_mask = attention_mask.to(device)
        batch_meta = batch_meta.to(device)
        batch_cred = batch_cred.to(device)
        batch_labels = batch_labels.to(device)

        optimizer.zero_grad()

        outputs = model(input_ids, attention_mask, batch_meta, batch_cred)

        loss = criterion(outputs.view(-1), batch_labels)

        loss.backward()

        optimizer.step()
        scheduler.step()

        epoch_loss += loss.item()


    
    avg_train_loss = epoch_loss / len(train_loader)

    # -------------------
    # VALIDATION
    # -------------------
    model.eval()

    correct = 0
    total = 0

    with torch.no_grad():

        for batch in val_loader:
            
            input_ids, attention_mask, batch_meta, batch_cred, batch_labels = batch

            input_ids = input_ids.to(device)
            attention_mask = attention_mask.to(device)
            batch_meta = batch_meta.to(device)
            batch_cred = batch_cred.to(device)
            batch_labels = batch_labels.to(device)

            outputs = model(input_ids, attention_mask, batch_meta, batch_cred)

            preds = (torch.sigmoid(outputs.squeeze()) > 0.5).float()

            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

    val_acc = correct / total
    if val_acc > best_val:
        best_val = val_acc
        torch.save(model.state_dict(), "best_model.pt")
        patience_counter = 0
    else:
        patience_counter += 1

    if patience_counter >= patience:
        print("Early stopping")
        break

   
    print(f"Epoch {epoch}")
    print("Train loss:", avg_train_loss)
    print("Validation accuracy:", val_acc)
    
# %%
